INCLUDE "emu8086.inc"

JMP START

DATA SEGMENT 
    PACKETS DW  0    ;NUMBER OF PACKETS TO BE TRANSMITTED
    N       DW  0    ;NUMBER OF TRANSMITTED PACKETS
    TOTAL   DW  0    ;TOTAL NUMBER OF TRANSMIISONS
    ASK     DW  "Enter number of packets: ",0
    SHOW    DW  "Number of Transmissions: ",0
DATA ENDS
   
CODE SEGMENT

ASSUME DS:DATA CS:CODE

START:
    MOV AX, DATA
    MOV DS, AX

    DEFINE_SCAN_NUM ;MACROS USED IN THE PROJECT
    DEFINE_PRINT_STRING
    DEFINE_PRINT_NUM
    DEFINE_PRINT_NUM_UNS 
    DEFINE_CLEAR_SCREEN

    LEA SI,ASK       ;ASK FOR NUMBER OF PACKETS
    CALL PRINT_STRING
    CALL SCAN_NUM    ;SCAN NUMBER OF PACKETS
    MOV PACKETS,CX

LOOP1: 
    INC TOTAL        ;INCREMENT TOTAL NUMBER OF TRANSMISSIONS   
    INC N            ;INCREMENT NUMBER OF TRANSMITTED PACKETS
    DEC PACKETS      ;DECREMENT NUMBER OF PACKETS TO BE TRANSMITTED

    CMP N, 64        ;CHECK IF 64 PACKETS HAVE BEEN TRANSMITTED
    JB  LESS         ;IF IT'S LESS THAN 64, JUMP TO LESS

    INC N            ;INCREMENT NUMBER OF TRANSMITTED PACKETS
    DEC PACKETS      ;DECREMENT NUMBER OF PACKETS TO BE TRANSMITTED
    JMP DONE

LESS: 
    MOV CX,N
    CMP CX,PACKETS
    JA  BREAK
    JE  BREAK
    SHL N,1           ;MULTIPLY N BY 2
    SUB PACKETS,CX    ;SUBTRACT CX FROM PACKETS

DONE:
    CMP PACKETS,0
    JB  BREAK
    JE  BREAK

    CMP N,128
    JNE END
    MOV N,0
END:
    JMP LOOP1

BREAK:
    PRINT 0AH
    PRINT 0DH
    LEA SI,SHOW
    CALL PRINT_STRING
    MOV AX,TOTAL
    CALL PRINT_NUM_UNS
    
CODE ENDS
END START
ret